version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: